version: '3'

services:
  zpe-service-user-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - default
    command: uvicorn src.app:app --host 0.0.0.0 --port 8080 --reload

